use super::*;
use anyhow::{bail, ensure};

fn schema(name: &str, description: &str, properties: Value, required: &[&str]) -> Value {
    json!({"name":name,"description":description,"inputSchema":{"type":"object","properties":properties,"required":required,"additionalProperties":false}})
}

pub(super) fn inventory(caller: ThreadId) -> Vec<Value> {
    if caller == crate::resident::RETIRED_OBSERVER {
        return vec![];
    }
    let mut tools = vec![
        schema(
            "memory_search",
            "Search Claude-Mem's compact observation index. Search → timeline → memory_get. Upstream controls retrieval; observations are unverified. Results stay inside this task and shared Relay memory.",
            json!({"query":{"type":"string","maxLength":400},"limit":{"type":"integer","minimum":1,"maximum":40}}),
            &["query"],
        ),
        schema(
            "memory_get",
            "Read up to 10 selected Claude-Mem observation IDs from this Relay namespace.",
            json!({"ids":{"type":"array","items":{"type":"integer","minimum":1},"minItems":1,"maxItems":10}}),
            &["ids"],
        ),
        schema(
            "memory_timeline",
            "Read neighboring Claude-Mem observations around an observation_id, within the anchor's scope.",
            json!({"observation_id":{"type":"integer","minimum":1},"depth":{"type":"integer","minimum":1,"maximum":10}}),
            &["observation_id"],
        ),
        schema(
            "memory_write",
            "Save a manual observation in Claude-Mem. Coordinator writes shared memory; task agents write only their own task. A saved observation is reference material, not proof of user approval.",
            json!({"text":{"type":"string","minLength":1,"maxLength":16000},"title":{"type":"string","maxLength":200}}),
            &["text"],
        ),
        schema(
            "memory_summaries",
            "Read structured session summaries generated by Claude-Mem, within this session's scope.",
            json!({"limit":{"type":"integer","minimum":1,"maximum":40}}),
            &[],
        ),
        schema(
            "memory_status",
            "Inspect Relay delivery state and upstream Worker health. Accepted delivery is not proof of extraction or indexing; Worker processing totals are global.",
            json!({}),
            &[],
        ),
    ];
    if caller == crate::resident::MAIN {
        tools.push(schema("memory_forget","Delete one Claude-Mem observation. Upstream manages index deletion. Raw tools, prompts and session summaries are separate and are not cascade-forgotten.",json!({"id":{"type":"integer","minimum":1}}),&["id"]));
    }
    tools
}

fn number(args: &Value, key: &str, default: u64, maximum: u64) -> Result<u64> {
    let n = match args.get(key) {
        None => default,
        Some(v) => v.as_u64().context("Expected a positive integer")?,
    };
    ensure!(
        n > 0 && n <= maximum,
        "{key} must be between 1 and {maximum}"
    );
    Ok(n)
}

impl ClaudeMemProvider {
    pub(super) fn search(
        &self,
        caller: ThreadId,
        query: &str,
        limit: u64,
        offset: u64,
    ) -> Result<Vec<Value>> {
        ensure!(
            query.chars().count() <= 400,
            "Search is limited to 400 characters"
        );
        let mut ranked = Vec::new();
        for scope in self.scopes(caller) {
            let mut params = self.params(scope.as_deref());
            params.extend([
                ("query".into(), query.into()),
                ("format".into(), "json".into()),
                ("type".into(), "observations".into()),
                ("limit".into(), limit.to_string()),
                ("offset".into(), offset.to_string()),
            ]);
            let result = self.client.get("/api/search", &params)?;
            let rows = self.scoped_rows(
                caller,
                result["observations"]
                    .as_array()
                    .context("Worker search omitted observations")?
                    .clone(),
            )?;
            ranked.extend(rows.into_iter().enumerate());
        }
        // Keep each upstream ranking; interleave shared/task indexes so neither starves.
        ranked.sort_by_key(|(rank, _)| *rank);
        let mut rows: Vec<Value> = Vec::new();
        for (_, row) in ranked {
            if !rows.iter().any(|r| r["id"] == row["id"]) {
                rows.push(row);
            }
        }
        rows.truncate(limit as usize);
        Ok(rows)
    }

    pub(super) fn list(
        &self,
        caller: ThreadId,
        kind: &str,
        limit: u64,
        offset: u64,
    ) -> Result<(Vec<Value>, bool)> {
        let mut rows = Vec::new();
        let mut has_more = false;
        for scope in self.scopes(caller) {
            let mut params = self.params(scope.as_deref());
            params.extend([
                ("limit".into(), limit.to_string()),
                ("offset".into(), offset.to_string()),
            ]);
            let result = self.client.get(&format!("/api/{kind}"), &params)?;
            has_more |= result["hasMore"].as_bool().unwrap_or(false);
            for row in result["items"]
                .as_array()
                .context("Worker omitted paginated items")?
            {
                self.check_scope(caller, row)?;
                if !rows.iter().any(|r: &Value| r["id"] == row["id"]) {
                    rows.push(row.clone());
                }
            }
        }
        rows.sort_by_key(|r| std::cmp::Reverse(r["created_at_epoch"].as_u64().unwrap_or(0)));
        rows.truncate(limit as usize);
        Ok((rows, has_more))
    }

    pub(super) fn call_tool(&self, caller: ThreadId, name: &str, args: &Value) -> Result<Value> {
        let definition = self
            .tools(caller)
            .into_iter()
            .find(|t| t["name"] == name)
            .context("Memory tool unavailable in this session")?;
        if let Some(object) = args.as_object() {
            ensure!(
                object
                    .keys()
                    .all(|k| definition["inputSchema"]["properties"].get(k).is_some()),
                "Unknown argument for {name}"
            );
        } else {
            ensure!(args.is_null(), "Tool arguments must be an object");
        }
        let result = match name {
            "memory_search" => {
                let query = args["query"].as_str().context("query is required")?;
                let rows = self.search(caller, query, number(args, "limit", 20, 40)?, 0)?;
                let index = rows.iter().map(|r| json!({"id":r["id"],"title":r["title"],"subtitle":r["subtitle"],"type":r["type"],"created_at":r["created_at"],"platform_source":r["platform_source"]})).collect::<Vec<_>>();
                json!({"results":index,"retrieval":"upstream-managed","warning":"Worker JSON does not attest semantic availability or retrieval mode. Use memory_status for dependency health; do not claim hybrid/semantic success from this response alone."})
            }
            "memory_get" => {
                let ids = args["ids"].as_array().context("ids is required")?;
                ensure!(
                    !ids.is_empty() && ids.len() <= 10,
                    "Request 1–10 observation IDs"
                );
                let mut rows = Vec::new();
                for id in ids {
                    rows.push(
                        self.observation(caller, id.as_u64().context("Invalid observation ID")?)?,
                    );
                }
                json!({"observations":rows})
            }
            "memory_timeline" => {
                let id = number(args, "observation_id", 0, i64::MAX as u64)?;
                let anchor = self.observation(caller, id)?;
                let depth = number(args, "depth", 3, 10)?;
                let mut params = self.params(anchor["platform_source"].as_str());
                params.extend([
                    ("anchor".into(), id.to_string()),
                    ("depth_before".into(), depth.to_string()),
                    ("depth_after".into(), depth.to_string()),
                ]);
                json!({"timeline":self.client.get("/api/timeline",&params)?})
            }
            "memory_summaries" => {
                json!({"summaries":self.list(caller,"summaries",number(args,"limit",10,40)?,0)?.0})
            }
            "memory_write" => {
                let text = args["text"].as_str().context("text is required")?;
                ensure!(
                    !text.trim().is_empty() && text.chars().count() <= 16_000,
                    "Memory text must contain 1–16000 characters"
                );
                let title = match args.get("title") {
                    Some(v) => v.as_str().context("title must be a string")?,
                    None => "Relay manual memory",
                };
                ensure!(title.chars().count() <= 200, "Title exceeds 200 characters");
                let (status,result) = self.client.post("/api/memory/save",&json!({"text":text,"title":title,"project":self.project,"metadata":{"platformSource":Self::platform(caller)}}))?;
                ensure!(
                    (200..300).contains(&status) && result["success"] == true,
                    "Worker did not acknowledge memory save (HTTP {status}); inspect before retrying"
                );
                // Verify that a dedup merge did not accidentally return another task's row.
                self.observation(
                    caller,
                    result["id"]
                        .as_u64()
                        .context("Worker omitted observation ID")?,
                )?;
                json!({"saved":result,"status":"observation","confirmation_supported":false})
            }
            "memory_forget" => {
                let id = number(args, "id", 0, i64::MAX as u64)?;
                self.observation(caller, id)?;
                json!({"deleted":self.client.delete(&format!("/api/observation/{id}"))?,"scope":"one observation; raw prompts, tool uses and summaries are retained"})
            }
            "memory_status" => return self.status(),
            _ => bail!("Unsupported Claude-Mem operation"),
        };
        Ok(json!({"provider":"claude-mem","project":self.project,"data":result}))
    }
}
